version: '3'
services:
  portfel:
    image: portfel
    restart: unless-stopped
    container_name: portfel
    volumes:
      - ./user_data:/usr/share/portfel
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_USER=${TELEGRAM_USER}
    command: >
      trade
      --config /usr/share/portfel/config.yml
      --database /usr/share/portfel/trades.db
