services:
  portfel:
    image: 038824004049.dkr.ecr.us-west-2.amazonaws.com/portfel
    restart: unless-stopped
    container_name: portfel
    volumes:
      - ./user_data:/usr/share/portfel
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_USER=${TELEGRAM_USER}
    command: >
      trade
      --config /usr/share/portfel/config.yml
      --database /usr/share/portfel/db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
