strategy: DiamondHands
minimum_balance: 500
expected_price_drop: 0.4
asset_weights:
  BTCUSDT: 0.5
  ADAUSDT: 0.1
  ETHUSDT: 0.07
  SOLUSDT: 0.05
  BNBUSDT: 0.05
  XRPUSDT: 0.03
  DOTUSDT: 0.025
  UNIUSDT: 0.025
  AVAXUSDT: 0.025
  LINKUSDT: 0.025
  TRXUSDT: 0.02
  TONUSDT: 0.02
  HBARUSDT: 0.02
  XLMUSDT: 0.02
  SUIUSDT: 0.02
