minimum_balance: 500
asset_weights:
  BTCBUSD: 0.5
  ADABUSD: 0.1
  ETHBUSD: 0.07
  SOLBUSD: 0.05
  BNBBUSD: 0.05
  DOTBUSD: 0.03
  AVAXBUSD: 0.025
  LINKBUSD: 0.025
  FTMBUSD: 0.025
  MATICBUSD: 0.025
  ROSEBUSD: 0.02
  MANABUSD: 0.02
  SANDBUSD: 0.02
  GALABUSD: 0.02
  AUDIOBUSD: 0.02
