minimum_balance: 500
asset_weights:
  BTCUSDT: 0.5
  ADAUSDT: 0.1
  ETHUSDT: 0.07
  SOLUSDT: 0.05
  LUNAUSDT: 0.05
  DOTUSDT: 0.03
  AVAXUSDT: 0.025
  LINKUSDT: 0.025
  FTMUSDT: 0.025
  MATICUSDT: 0.025
  ROSEUSDT: 0.02
  MANAUSDT: 0.02
  SANDUSDT: 0.02
  AUDIOUSDT: 0.02
  UNIUSDT: 0.02
