strategy: DiamondHands
minimum_balance: 500
expected_price_drop: 0.4
asset_weights:
  BTCUSDT: 0.29
  ETHUSDT: 0.25
  SOLUSDT: 0.08
  BNBUSDT: 0.05
  LINKUSDT: 0.05
  ARBUSDT: 0.05
  AAVEUSDT: 0.04
  OPUSDT: 0.03
  UNIUSDT: 0.03
  AVAXUSDT: 0.03
  NEARUSDT: 0.02
  SUIUSDT: 0.02
  XRPUSDT: 0.02
  ADAUSDT: 0.02
  DOTUSDT: 0.02